name: ✨ Feature Request
description: Suggest a new feature or improvement
title: '[FEATURE] '
labels: ['enhancement']
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it important?
      placeholder: 'Currently, there is no way to ...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the desired solution / feature.
      placeholder: 'The system should allow ...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternatives have you considered?
      placeholder: 'Another approach could be ...'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant info, links, or examples.
      placeholder: 'e.g., Screenshots, References, Mockups'
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define the criteria for considering the feature as complete.
      options:
        - label: Feature is implemented
        - label: Tests are provided
        - label: Documentation is updated
